### ISSUE TITLE
broken links

### ISSUE THREAD

**Issue by yoe** [yoe/planetgrep#12]
@andete 's new blog feed does not contain links to individual posts, resulting in the post headers referring back to Planet Grep itself.

Quid?

**Comment by andete** [comment]
Yes, I already was told this on facebook by Geert Goossens.
As I'm generating the Atom feed myself it looks like my template was missing a link part for the entry.
I've amended this and hopefully it is fixed now.

**Comment by andete** [comment]
In fact looking at planet.grep now it seems fixed all right ;)

cheers, Joost

**Comment by yoe** [comment]
Awesome, thanks. Sorry for the noise then :-)
